### ISSUE TITLE
include time in the output of `step` function of simulator.py

### ISSUE THREAD

**Issue by DamienAllonsius** [bcornelusse/microgridRLsimulator#1]
In `_decode_state`, it would be nice to add in the list:

```return [gridstate.non_steerable_consumption, gridstate.state_of_charge, gridstate.non_steerable_production]```

the entry: `gridstate.date_time`

**Comment by Shinpoo** [comment]
Done, the date time is added to the state space as the last element of the list.

**Comment by DamienAllonsius** [comment]
Is this modification made in commit 43b1fbd ? (Commit of branch release)

**Comment by Shinpoo** [comment]
Yes
